spring:
  application:
    name: popupmoah
  profiles:
    include: local
  datasource:
    url: jdbc:p6spy:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
server:
  port: 5032
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:defaultPassword}

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# 로그 설정
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/popupmoah.log

# AWS S3 설정
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}
    bucket-name: ${AWS_S3_BUCKET_NAME:popupmoah-files}
    region: ${AWS_S3_REGION:ap-northeast-2}

