spring:
  application:
    name: popupmoah
  profiles:
    include: local
  datasource:
    url: jdbc:p6spy:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30분 (밀리초)
      cache-null-values: false
server:
  port: 5032
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:defaultPassword}

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# CDN 설정
app:
  cdn:
    base-url: https://cdn.popupmoah.com
    image-path: /images
    thumbnail-path: /thumbnails
    default-image-url: /images/default-popup-store.jpg
    max-image-size: 10
    allowed-extensions:
      - jpg
      - jpeg
      - png
      - gif
      - webp
    thumbnail-size:
      width: 300
      height: 200
      quality: "80"

# 로그 설정
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/popupmoah.log
