spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/popupmoah
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8080

# Actuator 설정 (Prometheus 메트릭 활성화)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      access: public
  prometheus:
    metrics:
      export:
        enabled: true

# AWS S3 설정
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:popupmoah-files}
    region: ${AWS_S3_REGION:ap-northeast-2}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}

# 지도 API 설정
map:
  kakao:
    api-key: ${KAKAO_MAP_API_KEY:}
    geocoding-url: https://dapi.kakao.com/v2/local/search/address.json
    places-url: https://dapi.kakao.com/v2/local/search/keyword.json
  naver:
    client-id: ${NAVER_MAP_CLIENT_ID:}
    client-secret: ${NAVER_MAP_CLIENT_SECRET:}
    geocoding-url: https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode
    places-url: https://naveropenapi.apigw.ntruss.com/map-place/v1/search

logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.sgyj.popupmoah: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/popupmoah.log
    max-size: 10MB
    max-history: 30

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    display-operation-id: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
  show-actuator: true
